---
abstract: "CJM's plugins for Dist::Zilla"
author:
  - 'Christopher J. Madsen <perl@cjmweb.net>'
build_requires:
  File::pushd: 0
  Parse::CPAN::Meta: 0
  Test::DZil: 0
  Test::More: 0.88
  Try::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.009, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugins-CJM
no_index:
  directory:
    - corpus
recommends:
  Git::Wrapper: 0
requires:
  CPAN::Meta::Converter: 2.101550
  CPAN::Meta::Requirements: 2.121
  Data::Dumper: 0
  Dist::Zilla: 4.300009
  Dist::Zilla::Plugin::InlineFiles: 0
  Dist::Zilla::Plugin::MakeMaker: 4.300009
  File::Copy: 0
  File::HomeDir: 0.81
  File::Temp: 0.19
  Module::Metadata: 0
  Moose: 0
  Moose::Autobox: 0
  Moose::Role: 0
  Path::Class: 0
  Scalar::Util: 0
  autodie: 0
  namespace::autoclean: 0
  perl: 5.008
  version: 0.77
resources:
  repository: git://github.com/madsen/dist-zilla-plugins-cjm.git
version: 4.21
x_Dist_Zilla:
  perl:
    version: 5.018001
  plugins:
    -
      class: Dist::Zilla::Plugin::FileFinder::Filter
      name: ':CheckRecommend'
      version: 5.009
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: CJM/GatherDir
      version: 5.009
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: CJM/PruneCruft
      version: 5.009
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: CJM/ManifestSkip
      version: 5.009
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: CJM/MetaJSON
      version: 5.009
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: CJM/MetaYAML
      version: 5.009
    -
      class: Dist::Zilla::Plugin::License
      name: CJM/License
      version: 5.009
    -
      class: Dist::Zilla::Plugin::Test::PrereqsFromMeta
      name: CJM/Test::PrereqsFromMeta
      version: 4.21
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: CJM/PodSyntaxTests
      version: 5.009
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: CJM/PodCoverageTests
      version: 5.009
    -
      class: Dist::Zilla::Plugin::PodLoom
      config:
        Pod::Loom version: 0.06
      name: CJM/PodLoom
      version: 5.00
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: CJM/MakeMaker
      version: 5.009
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      name: CJM/RunExtraTests
      version: 0.011
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: CJM/MetaConfig
      version: 5.009
    -
      class: Dist::Zilla::Plugin::MatchManifest
      name: CJM/MatchManifest
      version: 4.01
    -
      class: Dist::Zilla::Plugin::RecommendedPrereqs
      name: CJM/RecommendedPrereqs
      version: 4.21
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: CJM/CheckPrereqsIndexed
      version: 0.009
    -
      class: Dist::Zilla::Plugin::GitVersionCheckCJM
      name: CJM/GitVersionCheckCJM
      version: 4.13
    -
      class: Dist::Zilla::Plugin::TemplateCJM
      name: CJM/TemplateCJM
      version: 4.21
    -
      class: Dist::Zilla::Plugin::Repository
      name: CJM/Repository
      version: 0.19
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: CJM/@Git/Check
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: CJM/@Git/Commit
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: CJM/@Git/Tag
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: CJM/@Git/Push
      version: 2.017
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: CJM/TestRelease
      version: 5.009
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: CJM/UploadToCPAN
      version: 5.009
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: CJM/ArchiveRelease
      version: 4.00
    -
      class: tools::CompileTests
      name: '=tools::CompileTests'
      version: ~
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: 5.009
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 5.009
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 5.009
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.009
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.009
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.009
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.009
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.009
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.009
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: 5.009
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: 5.009
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.009
